# This is a basic workflow that is manually triggered

name: Deploy to Github Pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # - name: Make public directory
    #   run: mkdir public

    # - name: Add Github Pages Repo
    #   uses: actions/checkout@v2
    #   with:
    #     repository: spencerc99/spencerchang.me
    #     path: './public'

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.13

    # - name: Build website and commit changes
    #   run: ./scripts/build-and-commit-changes.sh

    - name: Push changes to website
      uses: actions/checkout@v2
      run: ./deploy.sh
